@startuml

title __SRC's Class Diagram__\n

  namespace fran {
    class CollectionManager {
        {static} + ANSI_BLUE : String
        {static} + ANSI_RESET : String
        {static} + createCoordinates()
        {static} + createMovie()
        {static} + createPerson()
        {static} + help()
        {static} + info()
        {static} + print_ascending()
        {static} + print_field_descending_oscars_count()
        {static} + readDouble()
        {static} + readInt()
        {static} + readLong()
        {static} + readString()
        {static} + show()
        {static} + tryParseDouble()
        {static} + tryParseInt()
        {static} + tryParseLong()
        {static} ~ clear()
        {static} ~ count_less_than_oscars_count()
        {static} ~ executeScript()
        {static} ~ insert()
        {static} ~ remove()
        {static} ~ remove_greater_key()
        {static} ~ replaceIfGreater()
        {static} ~ replaceIfLower()
        {static} ~ save()
        {static} ~ update()
        {static} - createEye()
        {static} - createLocation()
        {static} - executeCommand()
        {static} - getMpaaRating()
        {static} - getNewId()
        {static} - readFloat()
        {static} - tryParseFloat()
    }
  }
  

  namespace fran {
    class Commander {
        {static} ~ fileName : String
        {static} ~ initialization : String
        {static} ~ movieHashtable : Hashtable<Long, Movie>
        {static} + handleConsoleCommand()
        {static} ~ continuar()
        {static} - getFileName()
    }
  }
  

  namespace fran {
    class CsvReader {
        + read()
        {static} - getEye()
        {static} - getMpaaRating()
    }
  }
  

  namespace fran {
    class Main {
        {static} + main()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
